version: "3.7"
networks:
  main:
    driver: overlay
services:
  hub:
    image: selenium/hub:3.141.59-zirconium
    ports:
      - "4444:4444"
    networks:
      - main
    deploy:
      mode: replicated
      replicas: 1
      labels:
        selenium.grid.type: "hub"
        selenium.grid.hub: "true"
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager ]
  chrome:
    image: selenium/node-chrome:3.141.59-zirconium
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
    volumes:
      - /dev/urandom:/dev/random
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 1
    networks:
      - main
    deploy:
      mode: replicated
      replicas: 10
      labels:
        selenium.grid.type: "node"
        selenium.grid.node: "true"
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
  firefox:
    image: selenium/node-firefox:3.141.59-zirconium
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
    volumes:
      - /dev/shm:/dev/shm
      - /dev/urandom:/dev/random
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 1
    networks:
      - main
    deploy:
      mode: replicated
      replicas: 10
      labels:
        selenium.grid.type: "node"
        selenium.grid.node: "true"
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
